spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driverClassName: org.h2.Driver


#Avrei voluto utilizzare la secret prendendola da qui piuttosto che hardcoded, così da non dover ricompilare il progetto in caso di cambio chiave o ttl,
# ma non sono riuscito a far riconoscere la proprietà anche provando diverse librerie, dà sempre Unknown property
#jwt:
#    secret: UKfjEW0ohJ^1gzk$EQb*Xm%5RP7O
#    expiration: 7200